//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUserLeave
    {
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public int UserID { get; set; }
        public int AppMasterLeaveTypeID { get; set; }
        public int AppLeaveTypeId { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int AppLeaveApprovedStatusId { get; set; }
        public bool IsActive { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public decimal TotalDays { get; set; }
        public bool IsPaidLeave { get; set; }
    
        public virtual AppLeaveApprovedStatu AppLeaveApprovedStatu { get; set; }
        public virtual AppLeaveType AppLeaveType { get; set; }
        public virtual AppMasterLeaveType AppMasterLeaveType { get; set; }
        public virtual AppUserLeave AppUserLeave1 { get; set; }
        public virtual AppUserLeave AppUserLeave2 { get; set; }
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
