//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVersionHistory
    {
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string VersionName { get; set; }
        public int VersionID { get; set; }
        public string Message { get; set; }
        public bool IsMustUpdate { get; set; }
        public int DeviceType { get; set; }
    }
}
