//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Break
    {
        public int BreakId { get; set; }
        public int UserId { get; set; }
        public System.DateTime BreakinTime { get; set; }
        public Nullable<System.DateTime> BreakoutTime { get; set; }
        public Nullable<bool> BreakinType { get; set; }
        public Nullable<int> BILocationId { get; set; }
        public string BILatitudeLongitude { get; set; }
        public Nullable<bool> BreakoutType { get; set; }
        public Nullable<int> BOLocationId { get; set; }
        public string BOLatitudeLongitude { get; set; }
        public string BreakinOutsideLocationReason { get; set; }
        public string BreakoutOutsideLocationReason { get; set; }
        public bool SystemBreakout { get; set; }
        public string BreakinDeviceId { get; set; }
        public string BreakoutDeviceId { get; set; }
        public int BreakTypeId { get; set; }
    }
}
