//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallIn
    {
        public long CId { get; set; }
        public long UserId { get; set; }
        public System.DateTime CallinTime { get; set; }
        public Nullable<System.DateTime> CalloutTime { get; set; }
        public string CallTitle { get; set; }
        public Nullable<bool> CallinType { get; set; }
        public Nullable<int> CILocationId { get; set; }
        public string CILatitudeLongitude { get; set; }
        public Nullable<bool> CalloutType { get; set; }
        public Nullable<int> COLocationId { get; set; }
        public string COLatitudeLongitude { get; set; }
        public bool SystemCallout { get; set; }
        public string CallTime { get; set; }
        public string CallinDeviceId { get; set; }
        public string CalloutDeviceId { get; set; }
        public string CallConclusion { get; set; }
    }
}
