//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.AppUserLeaves = new HashSet<AppUserLeave>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DefaultTimeFrom { get; set; }
        public System.DateTime DefaultTimeTo { get; set; }
        public int BreakCategoryId { get; set; }
        public System.DateTime LunchTimeFrom { get; set; }
        public System.DateTime LunchTimeTo { get; set; }
        public System.DateTime TeaTimeFrom { get; set; }
        public System.DateTime TeaTimeTo { get; set; }
        public int TotalBreakCount { get; set; }
        public int UserLimit { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserLeave> AppUserLeaves { get; set; }
    }
}
