//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddress
    {
        public int ID { get; set; }
        public long UserID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string CurrAddress { get; set; }
        public string CurrCity { get; set; }
        public string CurrState { get; set; }
        public string CurrPincode { get; set; }
        public string Country { get; set; }
        public string ImergencyCntNo { get; set; }
        public string ImergencyName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
