//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBankDetail
    {
        public long AccountId { get; set; }
        public Nullable<long> UserID { get; set; }
        public string BankAccountNo { get; set; }
        public string BankName { get; set; }
        public string BranchCode { get; set; }
        public string IFSCode { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string IPAddress { get; set; }
    }
}
