//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationPin
    {
        public long ID { get; set; }
        public int LocationID { get; set; }
        public string Lat { get; set; }
        public string PinAddress { get; set; }
        public string Long { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
