//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MId { get; set; }
        public string MenuName { get; set; }
        public string FormName { get; set; }
        public string IconName { get; set; }
        public Nullable<int> SortNumber { get; set; }
        public int PMId { get; set; }
        public bool IsActive { get; set; }
    }
}
