//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficialLeaf
    {
        public long ID { get; set; }
        public Nullable<byte> LeaveFor { get; set; }
        public Nullable<long> ObjectId { get; set; }
        public Nullable<System.DateTime> ApplicableFromDate { get; set; }
        public Nullable<System.DateTime> ApplicableToDate { get; set; }
        public Nullable<byte> LeaveTypeId { get; set; }
        public Nullable<int> LeaveTypeCount { get; set; }
        public Nullable<int> CarryForwarded { get; set; }
        public Nullable<int> LeavesTaken { get; set; }
        public Nullable<int> Balance { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<int> CreatedOn { get; set; }
        public Nullable<System.DateTime> CreatedBy { get; set; }
        public Nullable<int> UpdatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public string IPAddress { get; set; }
    }
}
