//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunchIn
    {
        public int PId { get; set; }
        public int UserId { get; set; }
        public System.DateTime PunchinTime { get; set; }
        public Nullable<System.DateTime> PunchoutTime { get; set; }
        public Nullable<bool> PunchinType { get; set; }
        public Nullable<int> PILocationId { get; set; }
        public string PILatitudeLongitude { get; set; }
        public Nullable<bool> PunchoutType { get; set; }
        public Nullable<int> POLocationId { get; set; }
        public string POLatitudeLongitude { get; set; }
        public string PunchinOutsideLocationReason { get; set; }
        public string PunchoutOutsideLocationReason { get; set; }
        public bool SystemPunchout { get; set; }
        public bool LatePunchin { get; set; }
        public string LatePunchinReason { get; set; }
        public bool EarlyPunchout { get; set; }
        public string EarlyPunchoutReason { get; set; }
        public string PunchinDeviceId { get; set; }
        public string PunchoutDeviceId { get; set; }
        public string WorkHourReason { get; set; }
        public string WorkingHour { get; set; }
        public string ExtraWorkingHour { get; set; }
        public bool IsHalfDay { get; set; }
        public bool PunchinOnHoliday { get; set; }
        public bool PunchinOnWeekoff { get; set; }
    }
}
