//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevice
    {
        public int UDId { get; set; }
        public int UserId { get; set; }
        public string DeviceId { get; set; }
        public string DeviceType { get; set; }
        public bool IsApproved { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Description { get; set; }
        public string AccessToken { get; set; }
        public int ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string DeviceName { get; set; }
        public string OSVersion { get; set; }
        public string LocationName { get; set; }
        public string IPAddress { get; set; }
    }
}
