//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersOTP
    {
        public long ID { get; set; }
        public long UserId { get; set; }
        public long OTP { get; set; }
        public string IPAddress { get; set; }
        public string DeviceID { get; set; }
        public string DeviceType { get; set; }
        public string LatLong { get; set; }
        public System.DateTime OTPSentTime { get; set; }
        public Nullable<bool> OTPSent { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    }
}
