//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AppUserLeaves = new HashSet<AppUserLeave>();
            this.AppUserLeaves1 = new HashSet<AppUserLeave>();
        }
    
        public int UserId { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public int RoleId { get; set; }
        public int TopId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> GenderTypeId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ProfilePic { get; set; }
        public string MaritalStatus { get; set; }
        public bool PunchinStatus { get; set; }
        public Nullable<int> EmployeeTypeId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string EmailID { get; set; }
        public string EmailIDPer { get; set; }
        public string MobileNoCmp { get; set; }
        public string PhoneNoPer { get; set; }
        public int LeaveApprovalTypeId { get; set; }
        public Nullable<int> LeaveApprovalSecondLevelId { get; set; }
        public Nullable<byte> Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserLeave> AppUserLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppUserLeave> AppUserLeaves1 { get; set; }
    }
}
