//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VersionMaster
    {
        public int VersionId { get; set; }
        public string PCVersion { get; set; }
        public string IOSVersion { get; set; }
        public string AndroidVersion { get; set; }
    }
}
