//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyTiming
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<byte> TimingFor { get; set; }
        public Nullable<long> ObjectId { get; set; }
        public string TimingType { get; set; }
        public string Day { get; set; }
        public Nullable<byte> DayType { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeUpto { get; set; }
        public System.TimeSpan WorkingHours { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string IPAddress { get; set; }
    }
}
