//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTask
    {
        public long ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public long UserID { get; set; }
        public long EmployeePunchID { get; set; }
        public string Task { get; set; }
        public bool IsDeleted { get; set; }
        public int Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual EmployeePunch EmployeePunch { get; set; }
    }
}
