//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string MessageType { get; set; }
        public string Message { get; set; }
        public Nullable<long> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public string DeviceID { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<long> EmployeePunchID { get; set; }
        public Nullable<long> EmployeeLeaveID { get; set; }
        public Nullable<long> EmployeeTaskID { get; set; }
        public Nullable<long> EmployeeCallID { get; set; }
        public bool HasSent { get; set; }
        public bool HasRead { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    }
}
